name: webm-converter  # Name of your app as it appears in the Snap Store
base: core18          # Switch to core18 to use gnome-3-28 extension for GTK3 support
version: '1.0.1'      # The version of your app
summary: A Flutter app for converting webm files to mp4 files  # Short description
description: |
  This is an open-source app written in Flutter that allows you to convert webm files to mp4 files.

grade: stable         # Use 'devel' for development versions
confinement: strict  # Use 'strict' confinement for better security if possible

icon: utils/icon/icon_512p_circle.png  # Path to the icon file

apps:
  webm-converter:
    command: ./video_converter
    desktop: webm-converter.desktop
    extensions:
      - gnome-3-28  # Add gnome-3-28 extension for GTK3 support with core18
    plugs:
      - network               # Access to the network for online resources
      - home                  # Access to user home directory
      - x11                   # Access to X11 for GUI applications
      - wayland               # Access to Wayland (if applicable)
      - opengl                # Access to OpenGL for rendering

parts:
  video-converter:
    plugin: dump
    source: build/linux/x64/release/bundle
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libgdk-pixbuf2.0-0  # Alternate naming for `libgdk-pixbuf-2.0-0`
      - libglib2.0-bin
      - shared-mime-info
      - hicolor-icon-theme
      - ffmpeg

