name: webm-converter
base: core18
version: "1.0.4"
summary: Legacy WebM to MP4 converter
description: |
  WEBM Converter is a legacy Flutter app that converts WebM files to MP4 files.

  This app will no longer be actively maintained because future development has moved to Armour Converter.

  Download Armour Converter on the Snap Store:
  https://snapcraft.io/armour-converter

  Armour Converter adds support for video, audio and image conversion, batch processing,
  quality and FPS controls, dark/light theme, and English/Italian languages.
  It is available for both AMD64 and ARM64, is more efficient, and includes more up-to-date features.

grade: stable
confinement: strict

icon: utils/icon/icon_512p_circle.png

apps:
  webm-converter:
    command: ./webm_converter
    desktop: webm-converter.desktop
    extensions:
      - gnome-3-28
    plugs:
      - home
      - network
      - x11
      - wayland
      - opengl
      - removable-media
      - audio-playback

parts:
  webm-converter:
    plugin: dump
    source: build/linux/x64/release/bundle
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - shared-mime-info
      - hicolor-icon-theme
      - ffmpeg
      - libglu1-mesa
      - freeglut3
      - libslang2
