name: webm-converter
base: core24
version: '1.0.3'
summary: A Flutter app for converting webm files to mp4 files
description: |
  This is an open-source app written in Flutter that allows you to convert webm files to mp4 files.

grade: stable
confinement: strict

icon: utils/icon/icon_512p_circle.png

apps:
  webm-converter:
    command: ./webm_converter  
    desktop: webm-converter.desktop
    extensions:
      - gnome
    plugs:
      - home
      - network
      - x11
      - wayland
      - opengl
      - removable-media
      - audio-playback
      - desktop
      - desktop-legacy
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"

parts:
  webm-converter:
    plugin: dump
    source: build/linux/arm64/release/bundle
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - shared-mime-info
      - hicolor-icon-theme
      - ffmpeg
      - libglu1-mesa
      - libslang2
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
