name: webm-converter
base: core18
version: '1.0.1'
summary: A Flutter app for converting webm files to mp4 files
description: |
  This is an open-source app written in Flutter that allows you to convert webm files to mp4 files.

grade: stable
confinement: strict

icon: utils/icon/icon_512p_circle.png

apps:
  webm-converter:
    command: ./video_converter
    desktop: webm-converter.desktop
    extensions:
      - gnome-3-28
    plugs:
      - home                # Access to user’s home directory
      - network             # Network access, if required
      - x11                 # Access to X11 for GUI applications
      - wayland             # Access to Wayland (if applicable)
      - opengl              # OpenGL access for rendering
      - removable-media     # Optional, if accessing external media like USB drives


parts:
  video-converter:
    plugin: dump
    source: build/linux/x64/release/bundle
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - shared-mime-info
      - hicolor-icon-theme
      - ffmpeg
      - libglu1-mesa              # Adds libGLU.so.1
      - freeglut3                 # Adds libglut.so.3
      - libslang2                 # Adds libslang.so.2

